// Utility functions for sharing tax results

export function generateTaxSummary(data) {
  const { taxType, inputs, outputs, regime, timestamp } = data;
  
  let summary = `Nigeria Tax Calculator - ${taxType} Results\n`;
  summary += `Generated: ${new Date(timestamp).toLocaleString()}\n`;
  summary += `Tax Regime: ${regime === "pre-2026" ? "Pre-2026 (PITA)" : "2026+ (Nigeria Tax Act 2025)"}\n\n`;
  
  summary += "INPUTS:\n";
  summary += "─".repeat(40) + "\n";
  Object.entries(inputs).forEach(([key, value]) => {
    if (value !== null && value !== undefined && value !== "") {
      summary += `${key}: ${typeof value === 'number' ? `₦${value.toLocaleString()}` : value}\n`;
    }
  });
  
  summary += "\nRESULTS:\n";
  summary += "─".repeat(40) + "\n";
  Object.entries(outputs).forEach(([key, value]) => {
    if (value !== null && value !== undefined) {
      summary += `${key}: ${typeof value === 'number' ? `₦${value.toLocaleString()}` : value}\n`;
    }
  });
  
  summary += "\n" + "─".repeat(40) + "\n";
  summary += "DISCLAIMER: This is an estimation for informational purposes only.\n";
  summary += "Always consult a qualified tax professional for official filings.\n";
  summary += "Generated by Nigeria Tax Calculator";
  
  return summary;
}

export function generateShareableLink(data) {
  // Create a base64 encoded string of the data
  const encoded = btoa(JSON.stringify(data));
  const baseUrl = window.location.origin;
  return `${baseUrl}/shared/${encoded}`;
}

export function decodeShareableLink(encoded) {
  try {
    return JSON.parse(atob(encoded));
  } catch (e) {
    return null;
  }
}

